version: '3.7'

services:
  app:
    container_name: pismo-challenge-app
    environment:
      working_dir: /var/app
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/app
    dns:
      - 8.8.8.8
#    depends_on:
#      - database
    networks:
      app_net:
        ipv4_address: 10.30.1.20

#  database:
#    container_name: pismo-challenge-mariadb
#    image: mariadb:10.5.2
#    restart: unless-stopped
#    ports:
#      - 3306:3306
#    volumes:
#      - mariadb-volume:/var/lib/mysql
#    environment:
#      TZ: "America/Sao_Paulo"
#      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
#      MYSQL_ROOT_PASSWORD: "root"
#      MYSQL_USER: 'giuseppe'
#      MYSQL_PASSWORD: '1q!Q'
#      MYSQL_DATABASE: 'pismo2023'
#    networks:
#      app_net:
#        ipv4_address: 10.30.1.22
#volumes:
#  mariadb-volume:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 10.30.1.1/24
